name: vehype
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 3.0.3+96

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  # Add the OmniDateTimePicker package from GitHub
  omni_datetime_picker:
    git:
      url: https://github.com/AhsinMehmood/OmniDateTimePicker.git



      # ref: main  # Optional: specify the branch, tag, or commit hash
  cupertino_icons: ^1.0.6
  logger: ^2.4.0
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  cloud_functions: 
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  share_plus: ^10.0.2

  provider: ^6.1.2
  firebase_storage: ^12.3.2
  sign_in_with_apple: ^6.1.3
  google_maps_flutter: ^2.9.0

  geolocator: ^10.1.1
  get: ^4.6.6
  cached_network_image: 
  shared_preferences: ^2.3.2
  flutter_svg: 
  # image_select: ^0.0.3
  # advanced_media_picker: ^0.0.16
  # flutter_image_compress: ^2.3.0
  # extended_image: ^8.2.1
  map_location_picker: 
  # media_picker_widget: ^1.0.7
  # mixpanel_flutter: ^2.3.1
  flutter_rating_bar: ^4.0.1
  firebase_database: ^11.1.4
  # interactive_slider: ^0.4.0
  # syncfusion_flutter_sliders: ^27.1.52
  # firebase_messaging: ^15.1.0
  
  image_picker: ^1.1.2
  multi_image_picker_plus: ^0.0.5
  video_player: ^2.9.1
  video_compress: ^3.1.3
  google_fonts:
  path_provider:
  dio: ^5.6.0
  ffmpeg_kit_flutter: ^6.0.3
  flick_video_player: ^0.9.0
  url_launcher:
  maps_launcher: ^2.2.1
  # add_2_calendar: ^3.0.1
  # swipeable_tile: ^2.0.1
  timeago: ^3.6.1
  flutter_staggered_grid_view: ^0.7.0
  # flutter_app_icon_badge: ^2.0.0
  # google_maps_place_picker_mb: ^3.1.2
  geoflutterfire_plus: ^0.0.29
  # rxdart: ^0.28.0
  readmore: ^3.0.0
  # image_cropper: ^7.0.5
  crop_your_image: ^1.1.0
  fuzzy: ^0.5.1
  toastification: ^2.0.0
  # omni_datetime_picker: ^2.0.4
  manage_calendar_events: ^2.0.3
  # google_fonts:
  onesignal_flutter: ^5.2.5

  sentry_flutter: ^8.8.0
  crypto: ^3.0.5
  http: ^1.2.2

  intl: any
  path: any
  flutter_google_maps_webservices: ^1.1.1
  tuple: ^2.0.2
  google_api_headers: 
  uuid: ^4.5.0
  firebase_ui_database: ^1.5.0
  font_awesome_flutter: ^10.7.0
  # searchfield: ^1.1.0
  # google_api_headers: ^4.2.1
  # flutter_google_maps_webservices: ^1.1.1
  # uuid: ^4.5.0
  # firebase_dynamic_links: ^6.0.5
  # uni_links: ^0.5.1
  just_audio: ^0.9.42
  # record: ^5.2.0
  audio_video_progress_bar: ^2.0.3
  just_waveform: ^0.0.5
  # event_bus: ^2.0.1
  flutter_audio_waveforms: ^1.2.1+8
  widget_marker_google_map: ^0.0.2
  # widget_to_marker: ^1.0.6
dev_dependencies:
  flutter_launcher_icons: ^0.13.1

  # package_rename: ^1.5.3
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

package_rename_config:
  android:
    app_name: "VEHYPE"
    package_name: "com.nomadllc.vehype"
   
  ios:
    app_name: "VEHYPE"
    bundle_name: "com.nomadllc.vehype"
    package_name: "com.nomadllc.vehype"


# flutter_intl:
#   enabled: true
flutter:

  uses-material-design: true
# flutter_launcher_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/icon.png"
  # min_sdk_android: 23// # android min sdk min:16, default 21
  # To add assets to your application, add an assets section, like this:
  
# package_rename_config:
#   android:
#     app_name: "VEHYPE"
#     package_name: "com.nomadllc.vehype"
#     override_old_package: # (Optional) (String) Use this to delete the old folder structure of MainActivity or to use the existing code with the new package name
#     lang: # (Optional) (String) The android development language {kotlin(default) or java}

#   ios:
#     app_name: "VEHYPE"
#     bundle_name: "com.nomadllc.vehype"
#     package_name: "com.nomadllc.vehype"

  
  
  
  
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    
    # - assets/theme.json
    # - assets/dark_theme.json    

  fonts:
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600
    - family: Poppins-Light
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 500
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
