name: vehype
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 3.0.3+66

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  cloud_functions:
  firebase_auth: ^5.1.0
  google_sign_in: ^6.2.1

  provider: ^6.1.2
  firebase_storage: ^12.0.1
  sign_in_with_apple: ^6.0.0
  google_maps_flutter: ^2.6.0

  geolocator: ^10.1.1
  get: ^4.6.6
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2
  flutter_svg: 
  image_select: ^0.0.3
  flutter_native_image: ^0.0.6+1
  extended_image: ^8.1.1
  map_location_picker: ^1.2.8+3
  mixpanel_flutter: ^2.2.0
  flutter_rating_bar: ^4.0.1
  firebase_database: ^11.0.1
  
  image_picker: ^1.0.7
  multi_image_picker_plus: ^0.0.4
  video_player: ^2.8.3
  video_compress: ^3.1.2
  path_provider:
  dio: ^5.4.1
  ffmpeg_kit_flutter: ^6.0.3
  flick_video_player: ^0.8.0
  url_launcher:
  maps_launcher: ^2.2.1
  onesignal_flutter: ^5.1.3
  add_2_calendar: ^3.0.1
  swipeable_tile: ^2.0.1
  timeago: ^3.6.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_app_badger: ^1.5.0
  google_maps_place_picker_mb: ^3.1.2
  geoflutterfire_plus: ^0.0.24
  rxdart: ^0.27.7
  readmore: ^3.0.0
  image_cropper: ^7.0.5
  crop_your_image: ^1.1.0
  fuzzy: ^0.5.1
  toastification: ^2.0.0
  omni_datetime_picker: ^2.0.3
  manage_calendar_events: ^2.0.3

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

  # package_rename: ^1.5.3
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

package_rename_config:
  android:
    app_name: "VEHYPE"
    package_name: "com.nomadllc.vehype"
   
  ios:
    app_name: "VEHYPE"
    bundle_name: "com.nomadllc.vehype"
    package_name: "com.nomadllc.vehype"


# flutter_intl:
#   enabled: true
flutter:

  uses-material-design: true
# flutter_launcher_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/icon.png"
#   min_sdk_android: 23 # android min sdk min:16, default 21
#   # To add assets to your application, add an assets section, like this:
  
# package_rename_config:
#   android:
#     app_name: "VEHYPE"
#     package_name: "com.nomadllc.vehype"
#     override_old_package: # (Optional) (String) Use this to delete the old folder structure of MainActivity or to use the existing code with the new package name
#     lang: # (Optional) (String) The android development language {kotlin(default) or java}

#   ios:
#     app_name: "VEHYPE"
#     bundle_name: "com.nomadllc.vehype"
#     package_name: "com.nomadllc.vehype"

  
  
  
  
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    # - assets/theme.json
    # - assets/dark_theme.json    

  fonts:
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600
    - family: Poppins-Light
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 500
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500